---@param theme AkiTheme
---@param colors AkiColors
return function(theme, colors)
  vim.g.terminal_color_0  = theme.bg0[1]
  vim.g.terminal_color_8  = theme.bg1[1]
  vim.g.terminal_color_1  = colors.kumo['3'][1]
  vim.g.terminal_color_9  = theme.sakura[1]
  vim.g.terminal_color_2 = theme.shinme[1]
  vim.g.terminal_color_10  = theme.sage[1]
  vim.g.terminal_color_3 = theme.sakaeru[1]
  vim.g.terminal_color_11  = theme.taiyo[1]
  vim.g.terminal_color_4 = theme.sukai[1]
  vim.g.terminal_color_12  = colors.kumo['1'][1]
  vim.g.terminal_color_5 = theme.seiun[1]
  vim.g.terminal_color_13  = colors.sakura['3'][1]
  vim.g.terminal_color_6 = theme.ike[1]
  vim.g.terminal_color_14  = colors.kumo['0'][1]
  vim.g.terminal_color_7 = theme.bg3[1]
  vim.g.terminal_color_15  = theme.fg2[1]
end
